//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xDC.Infrastructure.Application
{
    using System;
    using System.Collections.Generic;
    
    public partial class AmsdInflowFunds
    {
        public int Id { get; set; }
        public int FormHeaderId { get; set; }
        public string FundType { get; set; }
        public string Bank { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> LatestSubmission { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual FormHeader FormHeader { get; set; }
    }
}
