//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xDC.Infrastructure.Application
{
    using System;
    using System.Collections.Generic;
    
    public partial class App_Notification
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public string NotificationType { get; set; }
        public string NotificationIconClass { get; set; }
        public Nullable<bool> IsRead { get; set; }
        public string Title { get; set; }
        public string ShortMessage { get; set; }
        public string Message { get; set; }
        public System.DateTime CreatedOn { get; set; }
    }
}
