//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xDC.Infrastructure.Application
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit_RoleManagement
    {
        public int Id { get; set; }
        public string Activity { get; set; }
        public string Remarks { get; set; }
        public string Role { get; set; }
        public string PerformedBy { get; set; }
        public System.DateTime RecordedDate { get; set; }
    }
}
