//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xDC.Infrastructure.Application
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit_UserAccess
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public string ClientAddress { get; set; }
        public string ClientBrowser { get; set; }
        public Nullable<System.DateTime> RecordedDate { get; set; }
    }
}
