//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xDC.Infrastructure.Application
{
    using System;
    using System.Collections.Generic;
    
    public partial class EDW_Maturity_Deposit
    {
        public string Operator { get; set; }
        public string Bank { get; set; }
        public Nullable<System.DateTime> Value_Date { get; set; }
        public System.DateTime Maturity_Date { get; set; }
        public Nullable<double> Principle { get; set; }
        public Nullable<int> Tenor { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public string Asset_Type { get; set; }
        public string bank_code { get; set; }
        public string CURRENCY { get; set; }
    }
}
