//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xDC.Infrastructure.Application
{
    using System;
    using System.Collections.Generic;
    
    public partial class EDW_Maturity_MM
    {
        public string Operator { get; set; }
        public string Bank { get; set; }
        public System.DateTime ValueDate { get; set; }
        public System.DateTime MaturityDate { get; set; }
        public double Principle { get; set; }
        public int Tenor { get; set; }
        public double Rate { get; set; }
        public string AssetType { get; set; }
        public string BankCode { get; set; }
        public string Currency { get; set; }
        public string StockCode { get; set; }
        public double Price { get; set; }
        public string Issuer { get; set; }
    }
}
