//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xDC.Infrastructure.Application
{
    using System;
    using System.Collections.Generic;
    
    public partial class FID_TS10_OpeningBalance
    {
        public int Id { get; set; }
        public int FormId { get; set; }
        public string Account { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string FcaAccount { get; set; }
        public Nullable<decimal> FcaAmount { get; set; }
        public string AssignedBy { get; set; }
        public Nullable<System.DateTime> AssignedDate { get; set; }
    }
}
