//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xDC.Infrastructure.Application
{
    using System;
    using System.Collections.Generic;
    
    public partial class FID_Treasury_MMI
    {
        public int Id { get; set; }
        public int FormId { get; set; }
        public string CashflowType { get; set; }
        public string Dealer { get; set; }
        public string Issuer { get; set; }
        public string ProductType { get; set; }
        public string CounterParty { get; set; }
        public Nullable<System.DateTime> TradeDate { get; set; }
        public Nullable<System.DateTime> ValueDate { get; set; }
        public Nullable<System.DateTime> MaturityDate { get; set; }
        public Nullable<int> HoldingDayTenor { get; set; }
        public double Nominal { get; set; }
        public double SellPurchaseRateYield { get; set; }
        public double Price { get; set; }
        public double IntDividendReceivable { get; set; }
        public double Proceeds { get; set; }
        public double PurchaseProceeds { get; set; }
        public string CertNoStockCode { get; set; }
        public string FcaAccount { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
