//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xDC.Infrastructure.Application
{
    using System;
    using System.Collections.Generic;
    
    public partial class FID_MMI_Item
    {
        public int Id { get; set; }
        public string CashflowType { get; set; }
        public string Dealer { get; set; }
        public string Issuer { get; set; }
        public string ProductType { get; set; }
        public string CounterParty { get; set; }
        public Nullable<System.DateTime> ValueDate { get; set; }
        public Nullable<System.DateTime> MaturityDate { get; set; }
        public Nullable<int> HoldingDayTenor { get; set; }
        public Nullable<decimal> Nominal { get; set; }
        public Nullable<decimal> SellPurchaseRateYield { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> IntDividendReceivable { get; set; }
        public Nullable<decimal> Proceeds { get; set; }
        public Nullable<decimal> CertNoStockCode { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
