//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xDC.Infrastructure.Application
{
    using System;
    using System.Collections.Generic;
    
    public partial class Form_Workflow
    {
        public int Id { get; set; }
        public int FormId { get; set; }
        public string FormType { get; set; }
        public string RequestBy { get; set; }
        public string RequestTo { get; set; }
        public Nullable<System.DateTime> RecordedDate { get; set; }
        public string WorkflowStatus { get; set; }
        public string WorkflowNotes { get; set; }
    }
}
