//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xDC.Infrastructure.Application
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class kashflowDBEntities : DbContext
    {
        public kashflowDBEntities()
            : base("name=kashflowDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetActiveDirectoryUsers> AspNetActiveDirectoryUsers { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Config_Dropdown> Config_Dropdown { get; set; }
        public virtual DbSet<Config_Key> Config_Key { get; set; }
        public virtual DbSet<Config_Approver> Config_Approver { get; set; }
        public virtual DbSet<App_Notification> App_Notification { get; set; }
        public virtual DbSet<ISSD_FormHeader> ISSD_FormHeader { get; set; }
        public virtual DbSet<Config_Application> Config_Application { get; set; }
        public virtual DbSet<FID_Treasury> FID_Treasury { get; set; }
        public virtual DbSet<EDW_FID_List> EDW_FID_List { get; set; }
        public virtual DbSet<EDW_BankBalance> EDW_BankBalance { get; set; }
        public virtual DbSet<AMSD_IF> AMSD_IF { get; set; }
        public virtual DbSet<Form_Workflow> Form_Workflow { get; set; }
        public virtual DbSet<AMSD_IF_Item> AMSD_IF_Item { get; set; }
        public virtual DbSet<Config_FcaBankAccount> Config_FcaBankAccount { get; set; }
        public virtual DbSet<ISSD_TradeSettlement> ISSD_TradeSettlement { get; set; }
        public virtual DbSet<FID_Treasury_Deposit> FID_Treasury_Deposit { get; set; }
        public virtual DbSet<EDW_Maturity_Deposit> EDW_Maturity_Deposit { get; set; }
        public virtual DbSet<EDW_Maturity_MM> EDW_Maturity_MM { get; set; }
        public virtual DbSet<FID_Treasury_MMI> FID_Treasury_MMI { get; set; }
        public virtual DbSet<EDW_TradeItem> EDW_TradeItem { get; set; }
        public virtual DbSet<TenAmDealCutOff_ClosingBalance> TenAmDealCutOff_ClosingBalance { get; set; }
        public virtual DbSet<Audit_Form> Audit_Form { get; set; }
    }
}
