//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xDC.Infrastructure.Application
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class kashflowDBEntities : DbContext
    {
        public kashflowDBEntities()
            : base("name=kashflowDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetActiveDirectoryUsers> AspNetActiveDirectoryUsers { get; set; }
        public virtual DbSet<Amsd_InflowFunds> Amsd_InflowFunds { get; set; }
        public virtual DbSet<Iisd_TradeSettlement> Iisd_TradeSettlement { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Config_Application> Config_Application { get; set; }
        public virtual DbSet<Config_Dropdown> Config_Dropdown { get; set; }
        public virtual DbSet<Config_Key> Config_Key { get; set; }
        public virtual DbSet<Config_Approver> Config_Approver { get; set; }
        public virtual DbSet<App_Notification> App_Notification { get; set; }
        public virtual DbSet<Form_Header> Form_Header { get; set; }
        public virtual DbSet<Form_Workflow> Form_Workflow { get; set; }
    }
}
